name: 09c - Pasar informaciÃ³n con los artefactos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  tirar-dados:
    runs-on: ubuntu-latest
    steps:
      - name: Escribir dado 1
        run: echo "$((1 + RANDOM % 6))" >> dado1.txt
      - name: Escribir dado 2
        run: echo "$((1 + RANDOM % 6))" >> dado2.txt
      - name: Archivar resultado
        uses: actions/upload-artifact@v4
        with:
          name: dados
          path: |
            dado1.txt
            dado2.txt
  resumen:
    runs-on: ubuntu-latest
    needs: tirar-dados
    steps:
      - name: Descargar tirada de datos
        uses: actions/download-artifact@v4
        with:
          name: dados
      - name: Escribir resumen
        run: |
          echo ":dice: Resultados de los dados :dice:"
          echo "Dado 1": && cat dado1.txt >> $GITHUB_STEP_SUMMARY
          echo "Dado 2": && cat dado2.txt >> $GITHUB_STEP_SUMMARY


